spring:
  application:
    name: "umc10th"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/umc_study?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql:

# 9주차 JWT 관련 설정 추가
jwt:
  token:
    secret-key: ${JWT_SECRET_KEY}
    expiration:
      access: 1800000 # 30분